import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import Link from 'next/link';
import './globals.css';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<header className="sticky top-0 z-20 border-b border-black/10 dark:border-white/15 bg-background/80 backdrop-blur supports-[backdrop-filter]:bg-background/60">
					<nav className="mx-auto max-w-5xl px-4 py-3 flex items-center justify-between">
						<div className="flex items-center gap-4 text-sm">
							<Link href="/" className="hover:underline">
								Attendees
							</Link>
							<Link href="/chat" className="hover:underline">
								Chat
							</Link>
						</div>
						<div className="text-xs text-black/60 dark:text-white/60">
							MCP Demo
						</div>
					</nav>
				</header>
				{children}
			</body>
		</html>
	);
}
